import { HttpErrorResponse } from '@angular/common/http';
import { ChangeDetectionStrategy, Component, DestroyRef, computed, inject, signal } from '@angular/core';
import { takeUntilDestroyed } from '@angular/core/rxjs-interop';
import { RouterLink } from '@angular/router';
import { forkJoin } from 'rxjs';

import { LibraryApiService, LibraryItem, PlannedMovie, PlannedSeries, SeriesLibraryItem } from '../core/library-api.service';
import { DesktopFileService } from '../core/desktop-file.service';
import { isDesktopApp } from '../core/api-url';

@Component({ changeDetection: ChangeDetectionStrategy.OnPush, selector: 'app-library-page', imports: [RouterLink], styleUrl: './library.page.scss', template: `
  <div class="page library-page">
    <header class="collection-header"><div><p class="collection-label">Minha coleção</p><h1>Biblioteca</h1><p class="collection-copy">Escolha o que quer guardar por perto e encontre os arquivos locais em um só lugar.</p></div><dl class="collection-counts" aria-label="Resumo da biblioteca"><div><dt>Na lista</dt><dd>{{ plannedMovies().length + plannedSeries().length }}</dd></div><div><dt>Disponíveis</dt><dd>{{ items().length + availableSeries().length }}</dd></div></dl></header>
    <label class="library-search"><i class="ph ph-magnifying-glass" aria-hidden="true"></i><span class="sr-only">Buscar na biblioteca</span><input type="search" autocomplete="off" placeholder="Buscar títulos, versões ou arquivos" [value]="query()" (input)="updateQuery($event)" />@if (query()) { <button type="button" aria-label="Limpar busca" (click)="query.set('')"><i class="ph ph-x"></i></button> }</label>
    @if (state() === 'loading') { <section class="library-skeleton" aria-live="polite"><div class="skeleton-title"></div><div class="skeleton-rail"><i></i><i></i><i></i><i></i></div></section> } @else if (state() === 'error') { <section class="empty-library"><i class="ph ph-warning-circle" aria-hidden="true"></i><div><h2>Não foi possível abrir a biblioteca</h2><p>{{ errorMessage() }}</p><button class="btn btn-quiet" type="button" (click)="load()">Tentar novamente</button></div></section> } @else {
      @if (filteredPlanned().length) { <section class="planned-section" aria-labelledby="planned-title"><div class="section-heading"><div><h2 id="planned-title">Na sua lista</h2><p>Filmes salvos para decidir depois.</p></div><span>{{ filteredPlanned().length }}</span></div><div class="planned-grid">@for (movie of filteredPlanned(); track movie.tmdbId) { <article class="planned-film"><a [routerLink]="['/catalog', movie.tmdbId]" class="planned-poster">@if (movie.posterPath) { <img [src]="posterUrl(movie)" [alt]="'Pôster de ' + movie.title" /> } @else { <i class="ph ph-film-strip"></i> }</a><div class="planned-copy"><a [routerLink]="['/catalog', movie.tmdbId]">{{ movie.title }}</a><p>{{ year(movie) }}@if (movie.voteAverage !== null) { <span><i class="ph-fill ph-star"></i>{{ movie.voteAverage.toFixed(1) }}</span> }</p><button type="button" class="remove-planned" [disabled]="removingTmdbId() === movie.tmdbId" (click)="removePlanned(movie)"><i class="ph ph-x"></i>Remover da lista</button></div></article> }</div></section> }
      @if (filteredPlannedSeries().length) { <section class="planned-section" aria-labelledby="planned-series-title"><div class="section-heading"><div><h2 id="planned-series-title">Séries na sua lista</h2><p>Séries salvas para acompanhar por temporadas.</p></div><span>{{ filteredPlannedSeries().length }}</span></div><div class="planned-grid">@for (series of filteredPlannedSeries(); track series.tmdbId) { <article class="planned-film"><a [routerLink]="['/series', series.tmdbId]" class="planned-poster">@if (series.posterPath) { <img [src]="posterUrl(series)" [alt]="'Pôster de ' + series.name" /> } @else { <i class="ph ph-television"></i> }</a><div class="planned-copy"><a [routerLink]="['/series', series.tmdbId]">{{ series.name }}</a><p>{{ seriesYear(series) }}@if (series.voteAverage !== null) { <span><i class="ph-fill ph-star"></i>{{ series.voteAverage.toFixed(1) }}</span> }</p><button type="button" class="remove-planned" [disabled]="removingSeriesId() === series.tmdbId" (click)="removePlannedSeries(series)"><i class="ph ph-x"></i>Remover da lista</button></div></article> }</div></section> }
      @if (filteredAvailableSeries().length) { <section class="series-files-section" aria-labelledby="series-files-title"><div class="section-heading"><div><h2 id="series-files-title">Séries disponíveis</h2><p>Temporadas e episódios que já estão neste computador.</p></div><span>{{ filteredAvailableSeries().length }}</span></div><div class="series-library-grid">@for (series of filteredAvailableSeries(); track series.tmdbId) { <a class="series-library-card" [routerLink]="['/series', series.tmdbId]">@if (series.posterPath) { <img [src]="posterUrl(series)" [alt]="'Pôster de ' + series.title" /> } @else { <span><i class="ph ph-television"></i></span> }<div><strong>{{ series.title }}</strong><p>{{ seriesSummary(series) }}</p><small>{{ size(series.sizeBytes) }} armazenados</small></div></a> }</div></section> }
      @if (filteredItems().length) { <section class="files-section" aria-labelledby="files-title"><div class="section-heading"><div><h2 id="files-title">Arquivos locais</h2><p>Versões que já estão disponíveis neste computador.</p></div><span>{{ filteredItems().length }}</span></div><div class="library-list">@for (item of filteredItems(); track item.id) { <article class="library-row"><a [routerLink]="['/catalog', item.movieTmdbId]" class="library-poster">@if (item.posterPath) { <img [src]="posterUrl(item)" [alt]="'Pôster de ' + item.movieTitle" /> } @else { <i class="ph ph-film-strip"></i> }</a><div class="file-copy"><a [routerLink]="['/catalog', item.movieTmdbId]">{{ item.movieTitle }}</a><p>{{ quality(item) }} <span>{{ size(item.sizeBytes) }}</span></p><small>{{ item.relativePath }}</small></div><div class="library-actions">@if (desktop()) { <button class="icon-button" type="button" [disabled]="desktopActionId() === item.id" [attr.aria-label]="'Abrir ' + item.movieTitle + ' no VLC'" (click)="openInVlc(item)"><i class="ph ph-play"></i></button><button class="icon-button" type="button" [disabled]="desktopActionId() === item.id" [attr.aria-label]="'Mostrar ' + item.movieTitle + ' no Finder'" (click)="revealInFinder(item)"><i class="ph ph-folder-open"></i></button> }<button class="icon-button delete-file" type="button" [disabled]="deletingId() === item.id" [attr.aria-label]="'Excluir ' + item.movieTitle" (click)="remove(item)"><i class="ph ph-trash"></i></button></div></article> }</div></section> }
      @if (!filteredItems().length && !filteredPlanned().length && !filteredPlannedSeries().length && !filteredAvailableSeries().length) { <section class="empty-library" aria-labelledby="empty-library-title"><i class="ph" [class.ph-magnifying-glass]="query()" [class.ph-bookmark-simple]="!query()" aria-hidden="true"></i><div><h2 id="empty-library-title">{{ query() ? 'Nada corresponde à busca' : 'Sua coleção começa aqui' }}</h2><p>{{ query() ? 'Tente outro título ou limpe a busca.' : 'Abra um filme no catálogo e use “Adicionar à biblioteca” para criar sua lista.' }}</p>@if (query()) { <button class="btn btn-quiet" type="button" (click)="query.set('')">Limpar busca</button> } @else { <a class="btn btn-primary" routerLink="/catalog">Explorar catálogo</a> }</div></section> }
    }
  </div>` })
export class LibraryPage {
  private readonly libraryApi = inject(LibraryApiService); private readonly desktopFile = inject(DesktopFileService); private readonly destroyRef = inject(DestroyRef);
  readonly state = signal<'loading' | 'ready' | 'error'>('loading'); readonly items = signal<LibraryItem[]>([]); readonly seriesFiles = signal<SeriesLibraryItem[]>([]); readonly plannedMovies = signal<PlannedMovie[]>([]); readonly plannedSeries = signal<PlannedSeries[]>([]); readonly query = signal(''); readonly errorMessage = signal('Confira a conexão com o backend e tente novamente.'); readonly deletingId = signal<number | null>(null); readonly removingTmdbId = signal<number | null>(null); readonly removingSeriesId = signal<number | null>(null); readonly desktop = signal(isDesktopApp()); readonly desktopActionId = signal<number | null>(null);
  readonly availableSeries = computed(() => {
    const groups = new Map<number, { tmdbId: number; title: string; posterPath: string | null; files: SeriesLibraryItem[]; sizeBytes: number }>();
    for (const file of this.seriesFiles()) { const group = groups.get(file.seriesTmdbId) ?? { tmdbId: file.seriesTmdbId, title: file.seriesTitle, posterPath: file.posterPath, files: [], sizeBytes: 0 }; group.files.push(file); group.sizeBytes += file.sizeBytes; groups.set(file.seriesTmdbId, group); }
    return [...groups.values()];
  });
  readonly filteredItems = computed(() => this.items().filter((item) => this.matches([item.movieTitle, item.relativePath, this.quality(item)]))); readonly filteredAvailableSeries = computed(() => this.availableSeries().filter((series) => this.matches([series.title, this.seriesSummary(series), ...series.files.map((file) => file.relativePath)]))); readonly filteredPlanned = computed(() => this.plannedMovies().filter((movie) => this.matches([movie.title, movie.originalTitle ?? '', this.year(movie)]))); readonly filteredPlannedSeries = computed(() => this.plannedSeries().filter((series) => this.matches([series.name, series.originalName ?? '', this.seriesYear(series)])));
  constructor() { this.load(); }
  updateQuery(event: Event): void { this.query.set((event.target as HTMLInputElement).value); }
  load(): void { this.state.set('loading'); forkJoin({ items: this.libraryApi.browse(), seriesFiles: this.libraryApi.browseSeries(), planned: this.libraryApi.planned(), series: this.libraryApi.plannedSeries() }).pipe(takeUntilDestroyed(this.destroyRef)).subscribe({ next: ({ items, seriesFiles, planned, series }) => { this.items.set(items); this.seriesFiles.set(seriesFiles); this.plannedMovies.set(planned); this.plannedSeries.set(series); this.state.set('ready'); }, error: (error: unknown) => { if (error instanceof HttpErrorResponse && error.status === 0) this.errorMessage.set('O backend não está acessível.'); this.state.set('error'); } }); }
  posterUrl(item: LibraryItem | PlannedMovie | PlannedSeries | { posterPath: string | null }): string { return `https://image.tmdb.org/t/p/w342${item.posterPath}`; } year(movie: PlannedMovie): string { return movie.releaseDate ? movie.releaseDate.slice(0, 4) : 'Sem data'; } seriesYear(series: PlannedSeries): string { return series.firstAirDate ? series.firstAirDate.slice(0, 4) : 'Sem data'; } quality(item: LibraryItem): string { return [item.resolutionHeight ? `${item.resolutionHeight}p` : null, item.sourceType, item.dynamicRange].filter(Boolean).join(' · ') || 'Versão local'; } size(bytes: number): string { return bytes >= 1_000_000_000 ? `${(bytes / 1_000_000_000).toFixed(1)} GB` : `${Math.max(1, Math.round(bytes / 1_000_000))} MB`; }
  seriesSummary(series: { files: SeriesLibraryItem[] }): string { const episodes = series.files.filter((file) => file.episodeNumber !== null); const seasons = [...new Set(series.files.map((file) => file.seasonNumber).filter((season): season is number => season !== null))].sort((a, b) => a - b); if (episodes.length) return episodes.map((file) => `T${String(file.seasonNumber).padStart(2, '0')}E${String(file.episodeNumber).padStart(2, '0')}`).join(' · '); return `${seasons.map((season) => `Temporada ${season}`).join(' · ')} · ${series.files.length} arquivo${series.files.length === 1 ? '' : 's'}`; }
  removePlanned(movie: PlannedMovie): void { this.removingTmdbId.set(movie.tmdbId); this.libraryApi.removePlanned(movie.tmdbId).pipe(takeUntilDestroyed(this.destroyRef)).subscribe({ next: () => { this.plannedMovies.update((movies) => movies.filter((item) => item.tmdbId !== movie.tmdbId)); this.removingTmdbId.set(null); }, error: () => { this.errorMessage.set('Não foi possível remover este filme da lista.'); this.removingTmdbId.set(null); } }); }
  removePlannedSeries(series: PlannedSeries): void { this.removingSeriesId.set(series.tmdbId); this.libraryApi.removePlannedSeries(series.tmdbId).pipe(takeUntilDestroyed(this.destroyRef)).subscribe({ next: () => { this.plannedSeries.update((values) => values.filter((item) => item.tmdbId !== series.tmdbId)); this.removingSeriesId.set(null); }, error: () => { this.errorMessage.set('Não foi possível remover esta série da lista.'); this.removingSeriesId.set(null); } }); }
  remove(item: LibraryItem): void { if (this.desktop()) { this.desktopFile.confirmDeletion(item.movieTitle).then((confirmed) => { if (confirmed) this.deleteFile(item); }); return; } if (confirm(`Excluir o arquivo local de “${item.movieTitle}”? Esta ação não pode ser desfeita.`)) this.deleteFile(item); }
  openInVlc(item: LibraryItem): void { this.runDesktopAction(item, () => this.desktopFile.openInVlc(item.relativePath)); } revealInFinder(item: LibraryItem): void { this.runDesktopAction(item, () => this.desktopFile.revealInFinder(item.relativePath)); }
  private matches(values: string[]): boolean { const query = this.query().trim().toLocaleLowerCase(); return !query || values.some((value) => value.toLocaleLowerCase().includes(query)); } private deleteFile(item: LibraryItem): void { this.deletingId.set(item.id); this.libraryApi.remove(item.id).pipe(takeUntilDestroyed(this.destroyRef)).subscribe({ next: () => { this.items.update((items) => items.filter((current) => current.id !== item.id)); this.deletingId.set(null); }, error: () => { this.errorMessage.set('Não foi possível excluir este arquivo.'); this.deletingId.set(null); } }); } private runDesktopAction(item: LibraryItem, action: () => Promise<void>): void { this.desktopActionId.set(item.id); action().catch(() => this.errorMessage.set('Não foi possível acessar esse arquivo local. Confira se o Docker e o VLC estão ativos.')).finally(() => this.desktopActionId.set(null)); }
}
