import { ChangeDetectionStrategy, Component, DestroyRef, inject, signal } from '@angular/core';
import { takeUntilDestroyed } from '@angular/core/rxjs-interop';
import { ActivatedRoute, RouterLink } from '@angular/router';
import { CatalogApiService, PersonDetails } from '../core/catalog-api.service';

@Component({ changeDetection: ChangeDetectionStrategy.OnPush, selector: 'app-person-details-page', imports: [RouterLink], styleUrl: './person-details.page.scss', template: `
@if (person(); as details) { <div class="page person-page"><a class="back-link" routerLink="/catalog"><i class="ph ph-arrow-left"></i>Catálogo</a><header class="person-header">@if (details.profilePath) { <img [src]="'https://image.tmdb.org/t/p/w342' + details.profilePath" [alt]="details.name" /> } @else { <span><i class="ph ph-user"></i></span> }<div><p>Filmografia</p><h1>{{ details.name }}</h1>@if (details.biography) { <div class="bio">{{ details.biography }}</div> }</div></header><section><div class="section-heading"><h2>Filmes</h2><span>{{ details.movies.length }}</span></div><div class="person-grid">@for (movie of details.movies; track movie.tmdbId) { <a [routerLink]="['/catalog', movie.tmdbId]">@if (movie.posterPath) { <img [src]="'https://image.tmdb.org/t/p/w342' + movie.posterPath" [alt]="'Pôster de ' + movie.title" /> } @else { <span><i class="ph ph-film-strip"></i></span> }<strong>{{ movie.title }}</strong><small>{{ movie.releaseDate?.slice(0,4) || 'Sem data' }}</small></a> }</div></section></div> } @else { <div class="page person-state">Carregando pessoa.</div> }
` })
export class PersonDetailsPage { private readonly api = inject(CatalogApiService); private readonly route = inject(ActivatedRoute); private readonly destroyRef = inject(DestroyRef); readonly person = signal<PersonDetails | null>(null); constructor() { this.route.paramMap.pipe(takeUntilDestroyed(this.destroyRef)).subscribe(params => { const id = Number(params.get('tmdbId')); if (id) this.api.personDetails(id).pipe(takeUntilDestroyed(this.destroyRef)).subscribe({ next: person => this.person.set(person) }); }); } }
